apiVersion: helm.m.crossplane.io/v1beta1
kind: Release
metadata:
  name: url-drift-namespaced
  namespace: crossplane-system
  annotations:
    uptest.upbound.io/post-assert-hook: testhooks/url-drift.sh
spec:
  forProvider:
    chart:
      url: oci://ghcr.io/stefanprodan/charts/podinfo:6.10.1
    namespace: crossplane-system
  providerConfigRef:
    name: helm-provider-cluster
    kind: ClusterProviderConfig
