apiVersion: helm.m.crossplane.io/v1beta1
kind: Release
metadata:
  name: url-migration-namespaced
  namespace: crossplane-system
  annotations:
    uptest.upbound.io/post-assert-hook: testhooks/url-migration.sh
spec:
  forProvider:
    chart:
      name: podinfo
      repository: oci://ghcr.io/stefanprodan/charts
      version: 6.10.1
    namespace: crossplane-system
  providerConfigRef:
    name: helm-provider-cluster
    kind: ClusterProviderConfig
