apiVersion: helm.m.crossplane.io/v1beta1
kind: Release
metadata:
  name: url-spec-version-namespaced
  namespace: crossplane-system
  annotations:
    uptest.upbound.io/post-assert-hook: testhooks/url-spec-version.sh
spec:
  forProvider:
    chart:
      url: oci://ghcr.io/stefanprodan/charts/podinfo
      version: 6.10.0
    namespace: crossplane-system
  providerConfigRef:
    name: helm-provider-cluster
    kind: ClusterProviderConfig
