apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-patch
  namespace: wordpress
data:
  patch.yaml: |-
    patches:
      - patch: |-
          - op: add
            path: /spec/template/spec/nodeSelector
            value:
              node.size: big
              aws.az: us-west-2a
        target:
          kind: Deployment
---
apiVersion: helm.m.crossplane.io/v1beta1
kind: Release
metadata:
  name: wordpress-example-patched
  namespace: crossplane-system
spec:
  forProvider:
    namespace: wordpress
    chart:
      name: wordpress
      repository: https://charts.bitnami.com/bitnami
      version: 15.2.5
    values:
      param1: value1
      param2: 1
    set:
      - name: param1
        value: value2
    patchesFrom:
      - configMapKeyRef:
          key: patch.yaml
          name: wp-patch
          optional: false
  providerConfigRef:
    name: helm-provider-cluster
    kind: ClusterProviderConfig

