apiVersion: helm.crossplane.io/v1beta1
kind: Release
metadata:
  name: example-oci-url-embedded-digest
spec:
  forProvider:
    chart:
      # OCI URL with digest
      url: oci://ghcr.io/stefanprodan/charts/podinfo@sha256:c56f4d760bc9da702f231f37fcec89c66b0993f0cb91446f86d014b133c6693f
    namespace: crossplane-system
  providerConfigRef:
    name: helm-provider
