apiVersion: helm.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: default
spec:
  credentials:
    source: Secret
    secretRef:
      name: nebius
      namespace: upbound-system
      key: kubeconfig
  identity:
    type: NebiusServiceAccountCredentials
    source: Secret
    secretRef:
      name: nebius-credentials
      namespace: upbound-system
      key: credentials