apiVersion: helm.m.crossplane.io/v1beta1
kind: ClusterProviderConfig
metadata:
  name: helm-provider-cluster
  namespace: crossplane-system
spec:
  credentials:
    source: Secret
    secretRef:
      name: cluster-config
      namespace: crossplane-system
      key: kubeconfig
# identity:
#   type: GoogleApplicationCredentials
#   source: Secret
#   secretRef:
#     name: gcp-credentials
#     namespace: crossplane-system
#     key: credentials.json