## check provider-incluster.yaml for grant access
apiVersion: helm.m.crossplane.io/v1beta1
kind: ProviderConfig
metadata:
  name: helm-provider
  namespace: crossplane-system
spec:
  credentials:
    source: InjectedIdentity
